export const DEFAULT_ROLE_GROUPS = [
  {
    label: 'Engenharia (Técnico)',
    options: [
      'Engenheiro Trainee',
      'Engenheiro Júnior',
      'Engenheiro Pleno',
      'Engenheiro Sênior',
      'Engenheiro Especialista',
      'Engenheiro Consultor',
      'Pesquisador em Engenharia (R&D)',
    ],
  },
  {
    label: 'Engenharia (Liderança)',
    options: [
      'Líder Técnico (Tech Lead)',
      'Coordenador de Engenharia',
      'Supervisor de Engenharia',
      'Gerente de Engenharia',
      'Gerente de P&D',
      'Head de Engenharia',
      'Diretor Técnico (CTO)',
      'Diretor de Engenharia',
    ],
  },
  {
    label: 'Gestão / Projetos',
    options: [
      'Analista de Projetos',
      'Coordenador de Projetos',
      'Gerente de Projetos',
      'Gerente de Programa (PgM)',
      'Gerente de Portfólio',
      'PMO',
      'Scrum Master',
      'Product Owner',
      'Consultor',
    ],
  },
  {
    label: 'Produto / Dados / Tecnologia',
    options: [
      'Gerente de Produto (PM)',
      'Analista de Dados',
      'Cientista de Dados',
      'Engenheiro de Dados',
      'Engenheiro de Software',
      'Analista de Sistemas',
      'Arquiteto de Soluções',
      'Arquiteto de Software',
      'Analista de BI',
      'Especialista em IA/ML',
    ],
  },
  {
    label: 'Negócios / Operações',
    options: [
      'Analista de Negócios',
      'Coordenador de Operações',
      'Gerente de Operações',
      'Gerente Comercial',
      'Account Manager',
      'Customer Success',
      'Consultor de Negócios',
      'Analista Financeiro',
      'Gerente Financeiro',
    ],
  },
  {
    label: 'Carreira Acadêmica',
    options: [
      'Iniciação Científica',
      'Mestrando',
      'Doutorando',
      'Pós-Doutorando',
      'Pesquisador',
      'Professor',
      'Professor Doutor',
      'Professor Adjunto',
      'Professor Associado',
      'Professor Titular',
      'Coordenador de Curso',
    ],
  },
  {
    label: 'Setor Público / Forças Armadas',
    options: [
      'Servidor Público',
      'Analista de Órgão Público',
      'Especialista de Órgão Público',
      'Militar (Oficial)',
      'Militar (Praça)',
      'Professor Militar',
      'Pesquisador Militar',
    ],
  },
  {
    label: 'Empreendedorismo / Autônomo',
    options: [
      'Empreendedor',
      'Sócio-Fundador',
      'Diretor Executivo (CEO)',
      'Consultor Autônomo',
      'Freelancer',
      'Autônomo',
    ],
  },
  {
    label: 'Outros',
    options: [
      'Estagiário',
      'Trainee',
      'Analista',
      'Coordenador',
      'Gerente',
      'Diretor',
      'Prefiro não informar',
    ],
  },
];
