export const ALL_SKILLS = [
  'Acessibilidade Web',
  'Account Management',
  'Aconselhamento de Carreira',
  'Acústica Industrial',
  'Ações de Marketing',
  'Adaptabilidade',
  'Adestramento',
  'Administração de Empresas',
  'Administração de Redes',
  'Adobe Acrobat',
  'Adobe After Effects',
  'Adobe Illustrator',
  'Adobe Lightroom',
  'Adobe Photoshop',
  'Adobe Premiere Pro',
  'Adobe XD',
  'Aerodinâmica',
  'Aeronáutica',
  'Affiliate Marketing',
  'Agile Coaching',
  'Agronomia',
  'Alvenaria',
  'Almoxarifado',
  'Análise de Dados',
  'Análise de Riscos',
  'Análise de Sistemas',
  'Análise do Ciclo de Vida',
  'Análise Estatística',
  'Análise Fundamentalista',
  'Análise Técnica',
  'Android Development',
  'Animação 2D',
  'Animação 3D',
  'Antropologia',
  'Apicultura',
  'Apresentações de Alto Impacto',
  'Aquicultura',
  'Arbitragem',
  'Arquitetura de Dados',
  'Arquitetura de Interiores',
  'Arquitetura de Microsserviços',
  'Arquitetura de Nuvem',
  'Arquitetura de Software',
  'Arquitetura e Urbanismo',
  'Arquivologia',
  'Artes Marciais',
  'Artes Plásticas',
  'Articulação Política',
  'Artificial Intelligence',
  'ASIC Design',
  'Asphalt Paving',
  'Assembler',
  'Assessoria de Imprensa',
  'Assistência Social',
  'Astronomia',
  'Atendimento ao Cliente',
  'Atendimento Multicanal',
  'Atuária',
  'Auditoria Ambiental',
  'Auditoria Interna',
  'AutoCAD',
  'Automação de Marketing',
  'Automação Industrial',
  'Automação Predial',
  'Automotive Engineering',
  'AWS (Amazon Web Services)',
  'Azure',
  'Backend Development',
  'Bacteriologia',
  'Balanço Patrimonial',
  'Balé',
  'Banca de Investimento',
  'Bancos de Dados',
  'Barbearia',
  'Barman',
  'Bash Scripting',
  'Bases de Dados NoSQL',
  'Bases de Dados Relacionais',
  'Benchmarks',
  'Benefícios e Compensações',
  'BIM (Building Information Modeling)',
  'Bioinformática',
  'Biologia Marinha',
  'Biologia Molecular',
  'Biomedicina',
  'Biomimética',
  'Biotecnologia',
  'Blockchain',
  'Blog Writing',
  'Blueprints',
  'Bluetooth Technology',
  'Board Governance',
  'Bodywork',
  'Booking Systems',
  'Bootstrap',
  'Botânica',
  'Branding',
  'Bricklaying',
  'Broadcasting',
  'Budgeting',
  'Building Inspection',
  'Business Analysis',
  'Business Continuity Planning',
  'Business Intelligence',
  'Business Process Outsourcing',
  'Business Strategy',
  'C Programming',
  'C#',
  'C++',
  'CAD/CAM',
  'Cadeia de Suprimentos',
  'Calculus',
  'Calibração',
  'Call Center Operations',
  'Canto',
  'Captação de Recursos',
  'Carpintaria',
  'Cartografia',
  'Cash Flow Management',
  'Catering',
  'Células a Combustível',
  'Cenografia',
  'Cerâmica',
  'Certified Scrum Master',
  'Cibersegurança',
  'Ciência de Dados',
  'Ciência de Materiais',
  'Ciências Atuariais',
  'Ciências Políticas',
  'Circuitos Eletrônicos',
  'Citologia',
  'Civil Engineering',
  'Clean Code',
  'Climate Change Mitigation',
  'Cloud Computing',
  'CNC Management',
  'Coaching',
  'Cobol',
  'Cold Calling',
  'Comercialização',
  'Comércio Exterior',
  'Compliance',
  'Composição Musical',
  'Comunicação Assertiva',
  'Comunicação Visual',
  'Confeitaria',
  'Configuração de Redes',
  'Conformidade Regulatória',
  'Conservação Ambiental',
  'Construção Civil',
  'Contabilidade',
  'Contabilidade de Custos',
  'Controle de Qualidade',
  'Copywriting',
  'CorelDRAW',
  'Costura',
  'Cozinha Internacional',
  'Creative Writing',
  'Crédito e Cobrança',
  'CRM (Customer Relationship Management)',
  'Criptografia',
  'Cromatografia',
  'CSS3',
  'Culinária',
  'Customer Experience',
  'Customer Success',
  'Cybersecurity',
  'Danças Contemporâneas',
  'Dart',
  'Dashboard Design',
  'Data Analysis',
  'Data Engineering',
  'Data Mining',
  'Data Science',
  'Data Visualization',
  'Data Warehouse',
  'Day Trading',
  'Debt Collection',
  'Deep Learning',
  'Dental Surgery',
  'Dermatologia',
  'Design de Interiores',
  'Design de Moda',
  'Design de Produto',
  'Design de Serviço',
  'Design Gráfico',
  'Design Thinking',
  'Desktop Support',
  'DevOps',
  'DevSecOps',
  'Diagramação',
  'Dialética',
  'Didática',
  'Direito Administrativo',
  'Direito Civil',
  'Direito Digital',
  'Direito do Trabalho',
  'Direito Penal',
  'Direito Tributário',
  'Direção de Arte',
  'Direção de Fotografia',
  'Discurso Público',
  'DJing',
  'Django',
  'Docker',
  'Documentação Técnica',
  'Dropshipping',
  'E-commerce',
  'E-learning',
  'Econometria',
  'Economia Circular',
  'Economia Criativa',
  'Edição de Áudio',
  'Edição de Imagem',
  'Edição de Vídeo',
  'Educação a Distância',
  'Educação Especial',
  'Educação Física',
  'Educação Infantil',
  'Efeito de Partículas',
  'Eletricidade Industrial',
  'Eletricidade Predial',
  'Eletrônica Analógica',
  'Eletrônica de Potência',
  'Eletrônica Digital',
  'Eletrotécnica',
  'Elementos Finitos (FEA)',
  'Email Marketing',
  'Embedded Systems',
  'Empreendedorismo',
  'Endodontia',
  'Enfermagem',
  'Engenharia Acústica',
  'Engenharia Aeroespacial',
  'Engenharia Ambiental',
  'Engenharia Civil',
  'Engenharia de Alimentos',
  'Engenharia de Bioprocessos',
  'Engenharia de Controle e Automação',
  'Engenharia de Dados',
  'Engenharia de Manutenção',
  'Engenharia de Materiais',
  'Engenharia de Minas',
  'Engenharia de Petróleo',
  'Engenharia de Produção',
  'Engenharia de Redes',
  'Engenharia de Requisitos',
  'Engenharia de Segurança do Trabalho',
  'Engenharia de Software',
  'Engenharia de Tecidos',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Mecatrônica',
  'Engenharia Naval',
  'Engenharia Química',
  'Engenharia Reversa',
  'Entomologia',
  'EPIs',
  'ERP (Enterprise Resource Planning)',
  'Ergonomia',
  'Escrita Criativa',
  'Escrita Técnica',
  'Escultura',
  'Espanhol',
  'Espectroscopia',
  'Espeleologia',
  'Esporte de Alto Rendimento',
  'Esquemas Elétricos',
  'Estamparia',
  'Estatística Applied',
  'Estética',
  'Estoque',
  'Estruturas Metálicas',
  'Estudos de Mercado',
  'ETL Processes',
  'Etiqueta Empresarial',
  'Excel Avançado',
  'Facebook Ads',
  'Fact-checking',
  'Falcoaria',
  'Farmacologia',
  'Farmacovigilância',
  'Fashion Design',
  'Fechamento de Vendas',
  'Ferramentaria',
  'Field Sales',
  'Figma',
  'Filantropia',
  'Filmagem',
  'Filosofia',
  'Filtragem de Sinais',
  'Finanças Corporativas',
  'Finanças Pessoais',
  'Financial Modeling',
  'Física Médica',
  'Física Quântica',
  'Fisiologia do Exercício',
  'Fisioterapia',
  'Fitopatologia',
  'Flash Animation',
  'Flutter',
  'Fonoaudiologia',
  'Food Styling',
  'Forensics',
  'Fortran',
  'Fotografia Analógica',
  'Fotografia Digital',
  'Fotogrametria',
  'Francês',
  'Franquias',
  'Front-end Development',
  'Full-stack Development',
  'Fundraising',
  'Funilaria',
  'Fusões e Aquisições',
  'Game Design',
  'Game Development',
  'Gamificação',
  'Gastroenterologia',
  'Gastronomia',
  'Gatekeeping',
  'Gemologia',
  'Genética',
  'Geociências',
  'Geofísica',
  'Geografia',
  'Geologia',
  'Geomarketing',
  'Geometria Descritiva',
  'Geoprocessamento',
  'Georreferenciamento',
  'Gerenciamento de Ativos',
  'Gerenciamento de Crises',
  'Gerenciamento de Resíduos',
  'Geriatria',
  'Gestalt',
  'Gestão Ambiental',
  'Gestão Comercial',
  'Gestão da Cadeia de Suprimentos',
  'Gestão da Inovação',
  'Gestão da Qualidade',
  'Gestão de Categorias',
  'Gestão de Conflitos',
  'Gestão de Contratos',
  'Gestão de Custos',
  'Gestão de Desempenho',
  'Gestão de Energia',
  'Gestão de Equipes Remote',
  'Gestão de Facilidades',
  'Gestão de Frotas',
  'Gestão de Mudanças',
  'Gestão de Operações',
  'Gestão de Orçamentos',
  'Gestão de Parcerias',
  'Gestão de Pessoas',
  'Gestão de Portfólio',
  'Gestão de Processos',
  'Gestão de Produtos',
  'Gestão de Projetos',
  'Gestão de Riscos',
  'Gestão de Stakeholders',
  'Gestão de Talentos',
  'Gestão de Tempo',
  'Gestão de Tráfego Pago',
  'Gestão de Vendas',
  'Gestão do Conhecimento',
  'Gestão Educacional',
  'Gestão Estratégica',
  'Gestão Financeira',
  'Gestão Hospitalar',
  'Gestão hoteleira',
  'Gestão Industrial',
  'Gestão Logística',
  'Gestão Patrimonial',
  'Gestão Pública',
  'Git',
  'GitHub',
  'GitLab',
  'Glass Blowing',
  'Global Strategy',
  'Go (Golang)',
  'Google Ads',
  'Google Analytics',
  'Google Cloud Platform',
  'Google Search Console',
  'Governance, Risk, and Compliance',
  'Graffiti',
  'Graphic Design',
  'Green Belt',
  'Grooming',
  'Growth Hacking',
  'GUI Design',
  'Ginecologia',
  'Habilidades Interpessoais',
  'Hacking Ético',
  'Hadoop',
  'Hardware Design',
  'Haskell',
  'Health and Safety',
  'Heavy Equipment Operation',
  'Hematologia',
  'Hemerografia',
  'Hermenêutica',
  'Hidráulica',
  'Hidrologia',
  'Hidroponia',
  'Higienização Industrial',
  'Histologia',
  'História da Arte',
  'História Geral',
  'Holocracia',
  'Homeopatia',
  'Honestidade Intelectual',
  'Hospedagem de Sites',
  'Hospitalidade',
  'HTML5',
  'Human Resources',
  'Human-Computer Interaction',
  'Hybrid Cloud',
  'Hydraulics',
  'Hydrogeology',
  'Iberian Studies',
  'IBM Cloud',
  'Iconografia',
  'Ideação',
  'Identidade Visual',
  'Idiomas',
  'Iluminação de Palco',
  'Iluminação Pública',
  'Ilustração Digital',
  'Ilustração Médica',
  'Imobiliário',
  'Imunologia',
  'Inbound Marketing',
  'Inclusão Digital',
  'Indicadores de Desempenho (KPIs)',
  'Indústria 4.0',
  'Infectologia',
  'Inferência Estatística',
  'Influencer Marketing',
  'Informática',
  'Information Architecture',
  'Infográficos',
  'Inglês',
  'Inovação Aberta',
  'Inovação de Ruptura',
  'Inseminação Artificial',
  'Inside Sales',
  'Inspeção de Solda',
  'Instalações Elétricas',
  'Instalações Hidrossanitárias',
  'Instrumentation',
  'Instrução Técnica',
  'Insurance',
  'Inteligência Competitiva',
  'Inteligência de Mercado',
  'Inteligência Emocional',
  'Interface de Usuário (UI)',
  'Internal Audit',
  'International Business',
  'International Relations',
  'Internet das Coisas (IoT)',
  'Internet Marketing',
  'Interpretação de Texto',
  'Interpretação Simultânea',
  'Inventário',
  'Investigação Criminal',
  'Investimentos',
  'Ioga',
  'iOS Development',
  'IP Networking',
  'ISO 9001',
  'ISO 14001',
  'ISO 27001',
  'ISO 45001',
  'IT Service Management',
  'ITIL',
  'Jardinagem',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jornalismo',
  'Jornalismo de Dados',
  'Jornalismo Investigativo',
  'JSON',
  'Judo',
  'Jujutsu',
  'Julia (Linguagem)',
  'Jurisprudência',
  'Jury Selection',
  'Just-in-Time',
  'Kanban',
  'Karatê',
  'Key Opinion Leaders',
  'Key Performance Indicators',
  'Keynote',
  'Kotlin',
  'Kubernetes',
  'Labels and Tags',
  'Labor Relations',
  'Laboratórios de Análises Clínicas',
  'Landscaping',
  'Laravel',
  'Laser Cutting',
  'Latex',
  'Latu Sensu',
  'Law Enforcement',
  'Lead Generation',
  'Lean IT',
  'Lean Manufacturing',
  'Lean Six Sigma',
  'Lean Startup',
  'Leather Working',
  'Legal Writing',
  'Legislação Ambiental',
  'Legislação Trabalhista',
  'LGPD (Lei Geral de Proteção de Dados)',
  'Liability',
  'Liderança',
  'Liderança de Pensamento',
  'Liderança Situacional',
  'Linguagem Corporal',
  'Linguística',
  'Linux',
  'Lisp',
  'Litígio',
  'Lives Streaming',
  'Logística',
  'Logística Reversa',
  'Logo Design',
  'Lua (Linguagem)',
  'Lucratividade',
  'Ludicidade',
  'Luxury Goods',
  'Machine Learning',
  'Machine Vision',
  'Madrigal',
  'Magistério',
  'Magnetismo',
  'Mainframe',
  'Maintenance Management',
  'Maquiagem Profissional',
  'Management Consulting',
  'Manutenção Aeronáutica',
  'Manutenção Automotiva',
  'Manutenção de Computadores',
  'Manutenção Industrial',
  'Manufatura Aditiva',
  'Manufatura Enxuta',
  'Mapeamento de Processos',
  'Marcenaria',
  'Marketing de Conteúdo',
  'Marketing de Guerrilha',
  'Marketing de Influência',
  'Marketing de Relacionamento',
  'Marketing Digital',
  'Marketing Direto',
  'Marketing Político',
  'Marketplace Management',
  'Masonry',
  'Massoterapia',
  'Master Data Management',
  'MATLAB',
  'Matriz SWOT',
  'M&A',
  'Mechanical Design',
  'Mecânica de Fluidos',
  'Mecânica dos Solos',
  'Mecânica Geral',
  'Mecatrônica',
  'Medicina do Trabalho',
  'Medicina Esportiva',
  'Medicina Veterinária',
  'Medição de Precisão',
  'Meditação',
  'Melhoria de Processos',
  'Mensageria',
  'Mentoria',
  'Mercado de Capitais',
  'Merchandising',
  'Metaverse Development',
  'Metodologia Científica',
  'Metodologias Ágeis',
  'Metrologia',
  'Microbiologia',
  'Microcontroladores',
  'Microeconomia',
  'Microsoft Access',
  'Microsoft Azure',
  'Microsoft Excel',
  'Microsoft Outlook',
  'Microsoft PowerPoint',
  'Microsoft Project',
  'Microsoft Visio',
  'Microsoft Word',
  'Mineração de Dados',
  'Mixagem de Áudio',
  'Mobile Design',
  'Mobile Development',
  'Moda',
  'Modelagem 3D',
  'Modelagem de Dados',
  'Modelagem de Negócios',
  'Modelagem Financeira',
  'Moderação de Conteúdo',
  'Monitoramento Ambiental',
  'Monitoria de Qualidade',
  'Montagem de Infraestrutura',
  'Montagem Industrial',
  'MongoDB',
  'Morfologia',
  'Motion Design',
  'Motivation',
  'MS Project',
  'Multimedia',
  'Music Production',
  'Music Theory',
  'MySQL',
  'Nanotecnologia',
  'Narrativa',
  'Native Advertising',
  'Natural Language Processing (NLP)',
  'Navegação Aérea',
  'Navegação Marítima',
  'Nefrologia',
  'Negociação',
  'Negócios Internacionais',
  'Neo4j',
  'Net Promoter Score (NPS)',
  'Network Administration',
  'Network Engineering',
  'Network Security',
  'Neurociência',
  'Neurolinguística',
  'Neurologia',
  'Neuropsicologia',
  'Newsletters',
  'Node.js',
  'No-code Tools',
  'Non-profit Management',
  'NoSQL',
  'Nursing',
  'Nutrição Clínica',
  'Nutrição Esportiva',
  'Nutrologia',
  'Objective-C',
  'Obstetrícia',
  'Oceanografia',
  'Ocupational Safety',
  'Odoo',
  'Odontologia',
  'Office Administration',
  'Offshore Engineering',
  'Off-page SEO',
  'Oil and Gas',
  'OKR (Objectives and Key Results)',
  'On-page SEO',
  'Onboarding',
  'Ontologia',
  'Open Source',
  'Operating Systems',
  'Operação de Caixa',
  'Operação de Drones',
  'Operação de Empilhadeira',
  'Operações Bancárias',
  'Operações de Varejo',
  'Ophthalmic Surgery',
  'Oftalmologia',
  'Optometria',
  'Oracle Database',
  'Oratória',
  'Orçamento Público',
  'Orçamentação',
  'Organização de Eventos',
  'Organização de Fluxos de Trabalho',
  'Orientação a Objetos',
  'Ornitologia',
  'Ortodontia',
  'Ortopedia',
  'Otorrinolaringologia',
  'Outbound Sales',
  'Outsourcing',
  'PaaS',
  'Packaging Design',
  'Padrões de Projeto',
  'Paid Search',
  'Paisagismo',
  'Paleontologia',
  'Palestra',
  'Panificação',
  'Parsing',
  'Pascal',
  'Patrimônio Histórico',
  'Patrocínio',
  'PCP (Planejamento e Controle da Produção)',
  'PDCA',
  'Pediátrica',
  'Pedagogia',
  'Penitenciária',
  'Pensamento Crítico',
  'Pensamento Sistêmico',
  'Pension Funds',
  'Pentesting',
  'People Analytics',
  'Percepção Visual',
  'Performance Marketing',
  'Periodontia',
  'Perícia Civil',
  'Perícia Criminal',
  'Perícia Judicial',
  'Personal Training',
  'Pesquisa de Clima Organizacional',
  'Pesquisa de Mercado',
  'Pesquisa de Usuário (UR)',
  'Pesquisa e Desenvolvimento (P&D)',
  'Pesquisa Operacional',
  'Petrofísica',
  'PHP',
  'Pintura Automotiva',
  'Pintura Digital',
  'Pintura Industrial',
  'PL/SQL',
  'Planejamento de Carreira',
  'Planejamento de Demanda',
  'Planejamento de Mídia',
  'Planejamento Estratégico',
  'Planejamento Financeiro',
  'Planejamento Tributário',
  'Planejamento Urbano',
  'Plant Breeding',
  'PLC Programming',
  'Plumbing',
  'Podologia',
  'Poesia',
  'Policiamento',
  'Políticas Públicas',
  'Polímeros',
  'Português',
  'PostgreSQL',
  'Pós-Produção',
  'Power BI',
  'Power Electronics',
  'Power Pivot',
  'Power Query',
  'PowerShell',
  'PR (Public Relations)',
  'Práticas de Fabricação (GMP)',
  'Preaching',
  'Predictive Analytics',
  'Prensagem',
  'Preparações Microscópicas',
  'Preservação de Documentos',
  'Previdência Privada',
  'Pricing Strategy',
  'Primeiros Socorros',
  'Private Equity',
  'Proatividade',
  'Processamento de Imagens',
  'Processamento de Linguagem Natural',
  'Projetos Culturais',
  'Projetos Elétricos',
  'Projetos Hidráulicos',
  'Projetos Mecânicos',
  'Product Design',
  'Product Management',
  'Product Marketing',
  'Programação de CLP',
  'Programação Funcional',
  'Programação Linear',
  'Programação Orientada a Objetos',
  'Progressive Web Apps (PWA)',
  'Project Finance',
  'Project Management',
  'Project Management Office (PMO)',
  'Proofreading',
  'Propriedade Intelectual',
  'Prospecção de Clientes',
  'Prótese Dentária',
  'Prototipagem',
  'Prototipagem Rápida',
  'Psicanálise',
  'Psicologia Clínica',
  'Psicologia do Esporte',
  'Psicologia Educacional',
  'Psicologia Organizacional',
  'Psicopedagogia',
  'Psiquiatria',
  'Public Affairs',
  'Public Relations',
  'Public Speaking',
  'Publicidade',
  'Python',
  'PyTorch',
  'QA (Quality Assurance)',
  'QC (Quality Control)',
  'QGIS',
  'Qualidade de Software',
  'Química Analítica',
  'Química de Polímeros',
  'Química Farmacêutica',
  'Química Industrial',
  'Química Orgânica',
  'Quiropraxia',
  'RabbitMQ',
  'Radiologia',
  'Radioterapia',
  'Raku',
  'Raspberry Pi',
  'React Native',
  'React.js',
  'Real Estate',
  'Realidade Aumentada (AR)',
  'Realidade Virtual (VR)',
  'Recrutamento e Seleção',
  'Recursos Humanos',
  'Redação Acadêmica',
  'Redação de Conteúdo',
  'Redação Publicitária',
  'Redes de Computadores',
  'Redes Neurais',
  'Redis',
  'Redux',
  'Reforma Residencial',
  'Refrigeração',
  'Regulação de Sinistros',
  'Reinforcement Learning',
  'Relações com Investidores',
  'Relações Governamentais',
  'Relações Institucionais',
  'Relações Internacionais',
  'Relações Públicas',
  'Relatórios Financeiros',
  'Remuneração Estratégica',
  'Renewable Energy',
  'Reparação de Maquinaria',
  'Reporting',
  'Reprografia',
  'Requirements Engineering',
  'Research',
  'Resiliência',
  'Resolução de Conflitos',
  'Resolução de Problemas',
  'Responsabilidade Social',
  'Rest API',
  'Restauração de Obras de Arte',
  'Retail Management',
  'Retenção de Talentos',
  'Retórica',
  'Reumatologia',
  'Reverso Logística',
  'Revit',
  'Risk Management',
  'RPA (Robotic Process Automation)',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'SaaS',
  'Sales Management',
  'Sales Operations',
  'Salesforce',
  'SAP',
  'SAS',
  'Satisfação do Cliente',
  'Saúde Coletiva',
  'Saúde Mental',
  'Saúde Ocupacional',
  'Saúde Pública',
  'Scala',
  'Scikit-learn',
  'Scrum',
  'Search Engine Marketing (SEM)',
  'Search Engine Optimization (SEO)',
  'Secretariado Executivo',
  'Segurança da Informação',
  'Segurança de Dados',
  'Segurança do Trabalho',
  'Seguros',
  'Semiótica',
  'Sensoriamento Remoto',
  'SEO',
  'Service Design',
  'Servidores Linux',
  'Servidores Windows',
  'Shell Scripting',
  'Six Sigma',
  'Sketch',
  'SketchUp',
  'Social Media Marketing',
  'Sociologia',
  'Software Development',
  'Software Engineering',
  'Soluções em Nuvem',
  'Soldagem',
  'SolidWorks',
  'Sommelier',
  'Sourcing',
  'SPSS',
  'SQL',
  'SQL Server',
  'Stakeholder Management',
  'Standard Operating Procedures (SOP)',
  'Statistical Analysis',
  'Storyboarding',
  'Storytelling',
  'Strategic Planning',
  'Strategic Sourcing',
  'Strategy',
  'Supply Chain Management',
  'Suporte ao Cliente',
  'Suporte Técnico',
  'Sustainability',
  'Sustentabilidade',
  'Swift',
  'Symfony',
  'Systems Analysis',
  'Systems Engineering',
  'Tableau',
  'Tailwind CSS',
  'Tandem Computing',
  'Targeting',
  'Tax Law',
  'Tax Preparation',
  'Team Building',
  'Team Leadership',
  'Teamwork',
  'Technical Drawing',
  'Technical Recruiting',
  'Technical Support',
  'Technical Writing',
  'Tecnologia da Informação',
  'Telecomunicações',
  'Telemarketing',
  'Telemetria',
  'TensorFlow',
  'Teologia',
  'Terapia Cognitivo-Comportamental',
  'Terapia de Casal',
  'Terapia Ocupacional',
  'Test Driven Development (TDD)',
  'Testes de Penetração',
  'Testes de Software',
  'Testes Unitários',
  'Têxtil',
  'Time Management',
  'Toxicologia',
  'Trabalho em Equipe',
  'Tradução',
  'Tradução Simultânea',
  'Tráfego Pago',
  'Training and Development',
  'Transmissão de Calor',
  'Transmissão de Energia',
  'Transporte e Logística',
  'Tratamento de Água',
  'Tratamento de Efluentes',
  'Tratamento de Imagem',
  'Treinamento Corporativo',
  'Treinamento de Força',
  'Treinamento e Desenvolvimento',
  'Tributação',
  'Troubleshooting',
  'TypeScript',
  'Typography',
  'UML',
  'Underwriting',
  'Unit Testing',
  'Unity 3D',
  'Unix',
  'Unix Shell',
  'Urbanismo',
  'Usabilidade',
  'User Experience (UX)',
  'User Interface (UI)',
  'User Research',
  'Urologia',
  'Usina de Açúcar e Álcool',
  'Utilities',
  'UX Design',
  'UX Research',
  'UX Writing',
  'Varejo',
  'VBA',
  'Vendas',
  'Vendas B2B',
  'Vendas B2C',
  'Vendas Consultivas',
  'Vendas Diretas',
  'Vendas Externas',
  'Vendas Internas',
  'Vendas Online',
  'Vendas Porta a Porta',
  'Vendas Técnicas',
  'Venture Capital',
  'Veterinária',
  'Viabilidade Econômica',
  'Video Editing',
  'Video Production',
  'Vigilância Sanitária',
  'Virtualization',
  'Visão Computacional',
  'Visual Basic',
  'Visual Effects (VFX)',
  'Visual Identity',
  'Visual Merchandising',
  'Visual Studio',
  'Vitivinicultura',
  'VMware',
  'Voice Over',
  'Voz sobre IP (VoIP)',
  'Vue.js',
  'Vulnerability Assessment',
  'Warehouse Management',
  'Web Analytics',
  'Web Design',
  'Web Development',
  'Web Scraping',
  'Web Services',
  'Webflow',
  'Webpack',
  'Webinar Hosting',
  'Wellness Coaching',
  'Whiteboard Animation',
  'Wide Area Network (WAN)',
  'Windows Server',
  'Winemaking',
  'Wireframing',
  'Wireless Networking',
  'Wireshark',
  'Wolfram Mathematica',
  'WordPress',
  'Workday',
  'Workflow Automation',
  'Workplace Safety',
  'Writing',
  'Xen',
  'Xero',
  'XML',
  'X射线衍射 (XRD)',
  'YAML',
  'Yarn',
  'Yii',
  'Yoga',
  'YouTube Advertising',
  'YouTube Marketing',
  'Zabbix',
  'Zapier',
  'Zbrush',
  'Zend Framework',
  'Zendesk',
  'Zenith Navigation',
  'Zero Waste',
  'ZigBee',
  'Zootecnia',
  'Zope',
];
